framework:
  messenger:
    failure_transport: failed

    # Bus par défaut pour les messages système (emails, notifications, etc.)
    default_bus: command.bus

    buses:
      command.bus:
        middleware:
          - App\Infrastructure\Cqs\Middleware\CorrelationMiddleware
          - validation
          - doctrine_transaction
          - App\Infrastructure\Cqs\Middleware\LoggingMiddleware
          - App\Infrastructure\OpenTelemetry\Cqs\Middleware\OpenTelemetryMessagingAttributesMiddleware

      query.bus:
        middleware:
          - App\Infrastructure\Cqs\Middleware\CorrelationMiddleware
          - validation
          - App\Infrastructure\Cqs\Middleware\LoggingMiddleware
          - App\Infrastructure\OpenTelemetry\Cqs\Middleware\OpenTelemetryMessagingAttributesMiddleware

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: 'doctrine://default?queue_name=failed'
      # sync: 'sync://'

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      # Route your messages to the transports
      # 'App\Message\YourMessage': async


when@test:
  framework:
    messenger:
      transports:
        async: test://