services:
  # To test production build
#  php:
#    image: ghcr.io/jagfx/pyxis-php:latest
#    networks:
#      - app_network

  php:
    image: pyxis-php:latest
    container_name: pyxis-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: dev
    environment:
      XDEBUG_MODE: debug,coverage
      XDEBUG_SESSION: PHPSTORM
      XDEBUG_START_WITH_REQUEST: 1
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=pyxis
      SERVER_NAME: pyxis.local
      FRANKENPHP_CONFIG: ''

      # OpenTelemetry - Configuration simplifiée pour dev
      OTEL_PHP_AUTOLOAD_ENABLED: "true"
      OTEL_PHP_DEBUG_SCOPES_DISABLED: true
      OTEL_SERVICE_NAME: "pyxis"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_TRACES_SAMPLER: "always_on"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/symfony/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    depends_on:
      - otel-collector

  db:
    image: mysql:8.2
    container_name: pyxis-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: noPassword
      MYSQL_DATABASE: bugr
    volumes:
      - db-data:/var/lib/mysql
      - ./data/dumps:/dumps
    ports:
      - "3306:3306"
    networks:
      - app_network

  # ------ OpenTelemetry
  # Collector simplifié pour dev
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    container_name: otel_collector_dev
    command: [ "--config=/etc/otel-collector-dev.yml" ]
    volumes:
      - ./docker/otel/otel-collector-dev.yml:/etc/otel-collector-dev.yml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
#      - "4318:4318"   # OTLP HTTP
#      - "8888:8888"   # Metrics du collector
    environment:
     GOGC: 80  # Plus agressif sur le GC pour limiter la mémoire
    networks:
      - app_network
      - otel_network

volumes:
  db-data:

networks:
  app_network:
    name: pyxis_network
  otel_network:
    external: true
    name:  otel-network-bridge