shared:
  type: attribute
  resource: '../src/Shared/Controller/**/*'

domain:
  type: attribute
  resource: '../src/Domain/**/Controller/**/*'

module:
  type: attribute
  resource: '../src/Module/**/Controller/**/*'